version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
    container_name: freitagsfruehstueck-testcontainers-elasticsearch
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - freitagsfruehstueck-testcontainers

  crm:
    image: larmic/freitagsfruehstueck-testcontainers-crm-mock:latest
    container_name: freitagsfruehstueck-testcontainers-crm
    ports:
    - 8081:8080
    networks:
      - freitagsfruehstueck-testcontainers

networks:
  freitagsfruehstueck-testcontainers:
    driver: bridge

